name: Application Deployment
on:
  push:
    paths:
      - 'client/**'
      - 'server/**'
      - 'scripts/**'
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-southeast2
  ARTIFACT_REPO: dress-shop-repo
jobs:

  # Quality Gate
  # Step 1: Install dependencies and linting
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install & Lint
        run: |
          cd server && npm install && npm run lint
          cd ../client && npm install --legacy-peer-deps && npm run lint
    
