name: Application Deployment
on:
  push:
    paths:
      - 'client/**'
      - 'server/**'
      - 'scripts/**'
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-southeast2
  ARTIFACT_REPO: dress-shop-repo
jobs:
  # Step 1: Install Dependencies and Code Quality Check (Linting)
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Server Dependencies
        working-directory: ./server
        run: npm install

      - name: Lint Server
        working-directory: ./server
        run: npm run lint

      - name: Install Client Dependencies
        working-directory: ./client
        run: npm install --legacy-peer-deps

      - name: Lint Client
        working-directory: ./client
        run: npm run lint

  # Step 2: Jest Unit Tests
  jest-test:
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install client dependencies
        working-directory: ./client
        run: npm install --legacy-peer-deps
      - name: Run Jest (client)
        working-directory: ./client
        run: npm run test -- --coverage --coverageReporters=lcov --watchAll=false --forceExit
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            server/coverage/lcov.info
            client/coverage/lcov.info

  # Step 3: SonarCloud Analysis
  sonarcloud:
    needs: jest-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          name: coverage-reports
      - name: Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=raffi_devaa_dress-shop
            -Dsonar.organization=raffi_devaa
            -Dsonar.sources=client/src,server/src
            -Dsonar.tests=client/src,server/src
            -Dsonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts
            -Dsonar.javascript.lcov.reportPaths=server/coverage/lcov.info,client/coverage/lcov.info
            -Dsonar.qualitygate.wait=true
