name: Infrastructure Deployment

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
  pull_request:
    branches:
      - main
    paths:
      - "terraform/**"

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    env:
      TF_VAR_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}
      TF_VAR_REGION: ${{ secrets.REGION }}
      TF_VAR_DOMAIN: ${{ secrets.DOMAIN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Format Check
        working-directory: ./terraform
        run: terraform fmt -check

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan
